[workspace]
members = [
    "./libsfasta",
    "./sfa",
]

# This is magic
# [profile.dev.package."*"]
# opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units  = 1

[profile.dev]
debug = true
