[workspace]
members = [
	"libsfasta",
	"sfa"
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units  = 1
debug = 1

[profile.dev]
debug = true

[profile.dev.package."*"]
opt-level = 3
