max_width = 80
newline_style = "Unix"
normalize_comments = true
brace_style = "AlwaysNextLine"
reorder_imports = true
reorder_impl_items = true
reorder_modules = true
tab_spaces = 4
comment_width = 70
wrap_comments = true
imports_indent = "Block"
indent_style = "Block"
imports_granularity = "Crate"