block_size: 64
data:
  ids:
    compression_type: ZSTD
    compression_level: 7
  headers:
    compression_type: ZSTD
    compression_level: 7
  sequence:
    compression_type: ZSTD
    compression_level: 7
  masking:
    compression_type: ZSTD
    compression_level: 7
  quality:
    compression_type: ZSTD
    compression_level: 7
  signals:
    compression_type: ZSTD
    compression_level: 7
  modifications:
    compression_type: ZSTD
    compression_level: 7
index:
  ids:
    compression_type: ZSTD
    compression_level: 7
  headers:
    compression_type: ZSTD
    compression_level: 7
  sequence:
    compression_type: ZSTD
    compression_level: 7
  masking:
    compression_type: ZSTD
    compression_level: 7
  quality:
    compression_type: ZSTD
    compression_level: 7
  signals:
    compression_type: ZSTD
    compression_level: 7
  modifications:
    compression_type: ZSTD
    compression_level: 7
seqlocs:
  compression_type: ZSTD
  compression_level: -3
id_index:
  compression_type: ZSTD
  compression_level: -3
