block_size: 512
data:
  ids:
    compression_type: ZSTD
    compression_level: 9
  headers:
    compression_type: ZSTD
    compression_level: 9
  sequence:
    compression_type: ZSTD
    compression_level: 9
  masking:
    compression_type: ZSTD
    compression_level: 9
  quality:
    compression_type: ZSTD
    compression_level: 9
  signals:
    compression_type: ZSTD
    compression_level: 9
  modifications:
    compression_type: ZSTD
    compression_level: 9
index:
  ids:
    compression_type: ZSTD
    compression_level: 9
  headers:
    compression_type: ZSTD
    compression_level: 9
  sequence:
    compression_type: ZSTD
    compression_level: 9
  masking:
    compression_type: ZSTD
    compression_level: 9
  quality:
    compression_type: ZSTD
    compression_level: 9
  signals:
    compression_type: ZSTD
    compression_level: 9
  modifications:
    compression_type: ZSTD
    compression_level: 9
seqlocs:
  compression_type: ZSTD
  compression_level: 1
id_index:
  compression_type: ZSTD
  compression_level: 1