block_size: 64
data:
  ids:
    compression_type: ZSTD
    compression_level: 6
  headers:
    compression_type: ZSTD
    compression_level: 6
  sequence:
    compression_type: ZSTD
    compression_level: 6
  masking:
    compression_type: ZSTD
    compression_level: 6
  quality:
    compression_type: ZSTD
    compression_level: 6
  signals:
    compression_type: ZSTD
    compression_level: 6
  modifications:
    compression_type: ZSTD
    compression_level: 6
index:
  ids:
    compression_type: ZSTD
    compression_level: 6
  headers:
    compression_type: ZSTD
    compression_level: 6
  sequence:
    compression_type: ZSTD
    compression_level: 6
  masking:
    compression_type: ZSTD
    compression_level: 6
  quality:
    compression_type: ZSTD
    compression_level: 6
  signals:
    compression_type: ZSTD
    compression_level: 6
  modifications:
    compression_type: ZSTD
    compression_level: 6
seqlocs:
  compression_type: ZSTD
  compression_level: -3
id_index:
  compression_type: ZSTD
  compression_level: -3
