[package]
name = "libsfasta"
version = "0.0.1"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_bytes = "0.11.5"
crossbeam = "0.8.0"
thincollections = "0.5.3"
flate2 = { version = "1.0.20" }
static_assertions = "1.1.0"
snap = "1.0.5"
bincode = "1.3.3"
bumpalo = { version = "3.6.1", features = ["collections", "boxed"] }
zstd = {version = "0.8.0", features = [ "experimental", "zstdmt"] }
lz4 = "1.23.1"
hashbrown = { version = "0.11.2", features = ["serde"] }
rand = "0.8.3"
rand_core = "0.6.2"
rand_chacha = "0.3.0"
lz4_flex = "0.7.5"
bitpacking = "0.8.4"
twox-hash = "1.6.0"
serde-big-array = {version = "0.3.2", features = ["const-generics"]}

[dev-dependencies]
criterion = "0.3"
humansize = "1.1.0"

[[bench]]
name = "indexing"
harness = false