[package]
name = "libsfasta"
version = "0.0.1"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "dylib"]

[profile.release]
debug = true

# Add in xz compression support

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_bytes = "0.11.5"
crossbeam = "0.8.1"
# thincollections = "0.5.3"
static_assertions = "1.1.0"
bincode = "1.3.3"
hashbrown = { version = "0.11.2" } #, features = ["serde"] }
rand = "0.8.4"
rand_core = "0.6.3"
rand_chacha = "0.3.1"
bytelines = "2.2.2"
simdutf8 = "0.1.3"
rayon = "1.5.1"
itertools = "0.10.1"
# mimalloc = { version = "*", default-features = false }
bumpalo = {version = "3.7.0", features = ["collections"]}

# Hashers
twox-hash = "1.6.0"
ahash = "0.7.3"

# Compression algorithms
lz4_flex = "0.8.2"
# zstd = {version = "0.8.1", features = [ "experimental" ] }
zstd = { version="0.9.0", features=["experimental"] } # { git = "https://github.com/gyscos/zstd-rs", features = [ "experimental" ] }
xz = "0.1.0"
flate2 = { version = "1.0.20", features = ["zlib-ng-compat"], default-features = false }
snap = "1.0.5"
brotli = "3.3.0"
bitpacking = "0.8.4"

[dev-dependencies]
criterion = "0.3"
humansize = "1.1.0"
generic-array = "0.14.4"
numeric-array = "0.5.2"
num-traits = "0.2.14"
ux_serde = "0.2.0"

[[bench]]
name = "indexing"
harness = false

[[bench]]
name = "compression"
harness = false

[[bench]]
name = "conversion"
harness = false
