[package]
name = "sfa"
version = "0.2.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
#lto = "fat"
#codegen-units = 1
#debug = true

[dependencies]
git-version = "0.3.5"
indicatif = "0.17.0"
flate2 = { version = "1.0.23", features = ["zlib-ng-compat"], default-features = false }
hashbrown = { version = "0.12.1" } #, features = ["serde"] }
rand = "0.8.5"
rand_core = "0.6.3"
rand_chacha = "0.3.1"
# Is this even needed here?
bincode = { version = "2.0.0-rc.1" } #, features = ["serde"] }
mimalloc = { version = "0.1.29", default-features = false }
snap = "1.0.5"
crossbeam = "0.8.1"
bytelines = "2.4.0"
toml = "0.5.9"
simdutf8 = "0.1.4"
bumpalo = {version = "3.10.0", features = ["collections"]}
core_affinity = "0.5.10" # Not used yet...
libsfasta = { path = "../libsfasta/" }
log = "0.4.17"
env_logger = "0.9.0"

[dependencies.clap]
version = "3.2.8"
features = [ "suggestions", "derive", "cargo", "color", "wrap_help"]

[[bin]]
name = "sfa"
test = true
bench = true
