[package]
name = "sfa"
version = "0.2.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[dependencies]
indicatif = "0.16.0"
libsfasta = { path = "../libsfasta/" }
serde = { version = "1.0.125", features = ["derive"] }
hashbrown = { version = "0.11.2", features = ["nightly", "serde"] }
rand = "0.8.3"
rand_core = "0.6.2"
rand_chacha = "0.3.0"
bincode = "1.3.3"

[dependencies.clap]
version = "3.0.0-beta.2"
features = [ "suggestions", "color", "yaml", "wrap_help"]
