[package]
name = "sfa"
version = "0.2.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = "fat"
# panic = "abort"
codegen-units = 1
# debug = true

[dependencies]
indicatif = "0.16.0"
libsfasta = { path = "../libsfasta/" }
serde = { version = "1.0.126", features = ["derive"] }
flate2 = { version = "1.0.20", features = ["zlib-ng-compat"], default-features = false }
hashbrown = { version = "0.11.2", features = ["serde"] }
rand = "0.8.4"
rand_core = "0.6.3"
rand_chacha = "0.3.1"
bincode = "1.3.3"
mimalloc = { version = "*", default-features = false }
snap = "1.0.5"
crossbeam = "0.8.1"
bytelines = "2.2.2"
toml = "0.5.8"
simdutf8 = "0.1.3"


[dependencies.clap]
version = "3.0.0-beta.2"
features = [ "suggestions", "color", "yaml", "wrap_help"]

[[bin]]
name = "sfa"
test = true
bench = true
